'use strict';
const $ = s => document.querySelector(s);
const RWL_GATEWAY = 'https://rwl-movies-gateway.rwl98.workers.dev';
const state = {gateway:RWL_GATEWAY,lang:localStorage.getItem('rwlLang')||'ar',home:null,hero:null,searchTimer:null,detail:null,detailType:null,servers:[],activeServer:null};
const imgBase = 'https://image.tmdb.org/t/p/';
function typeOf(x){return x.media_type==='tv'||(!x.title&&x.name)?'tv':'movie'}
function titleOf(x){return x.title||x.name||x.original_title||x.original_name||'Untitled'}
function dateOf(x){return (x.release_date||x.first_air_date||'').slice(0,4)}
function posterURL(x,size='w500'){return x?.poster_path?`${imgBase}${size}${x.poster_path}`:''}
function backdropURL(x,size='w1280'){return x?.backdrop_path?`${imgBase}${size}${x.backdrop_path}`:''}
function text(s){return String(s??'')}
function esc(s){return text(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2400)}
function setStatus(msg){$('#status').textContent=msg}
function open(id){$('#'+id).classList.add('open')}
function close(id){$('#'+id).classList.remove('open')}
async function api(path){const r=await fetch(state.gateway+path,{headers:{Accept:'application/json'}});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.message||`HTTP_${r.status}`);return b}
function card(item){const t=esc(titleOf(item)),year=esc(dateOf(item)),type=typeOf(item),id=Number(item.id)||0,p=posterURL(item);return `<article class="card ${p?'':'placeholder'}" data-id="${id}" data-type="${type}">${p?`<img loading="lazy" src="${p}" alt="${t}">`:'RWL'}<div class="cardShade"></div><div class="cardCopy"><b>${t}</b><small>${year}${year?' • ':''}${type==='tv'?'TV':'Movie'}${item.vote_average?` • ★ ${Number(item.vote_average).toFixed(1)}`:''}</small></div></article>`}
function row(el,items){$(el).innerHTML=(items||[]).filter(x=>x&&x.id&&(x.media_type!=='person')).slice(0,20).map(card).join('')||'<div style="color:#777;padding:20px">لا توجد نتائج</div>'}
function applyHero(item){if(!item)return;state.hero=item;const bg=backdropURL(item);$('#hero').style.backgroundImage=bg?`linear-gradient(125deg,#10172244,#21152355),url("${bg}")`:'';$('#heroTitle').textContent=titleOf(item);$('#heroOverview').textContent=item.overview||'لا يوجد وصف متاح.';$('#heroMeta').textContent=[dateOf(item),typeOf(item)==='tv'?'مسلسل':'فيلم',item.vote_average?`★ ${Number(item.vote_average).toFixed(1)}`:''].filter(Boolean).join(' • ')}
async function loadHome(){setStatus('جاري الاتصال بـ RWL…');try{const b=await api(`/v1/tmdb/home?language=${state.lang==='ar'?'ar-SA':'en-US'}`);state.home=b;row('#trendingRow',b.trending);row('#moviesRow',b.movies);row('#tvRow',b.tv);applyHero((b.trending||[]).find(x=>x.media_type!=='person')||b.movies?.[0]||b.tv?.[0]);setStatus('متصل بـ RWL')}catch(e){setStatus('تعذر الاتصال بـ RWL');toast(e.message==='TMDB_NOT_CONFIGURED'?'TMDB غير مفعّل في RWL Gateway':'تعذر الوصول إلى RWL Gateway');console.error('RWL Gateway error:',e)}}
function resetSources(message=''){state.servers=[];$('#directSources').innerHTML='';$('#p2pSources').innerHTML='';$('#directLane').hidden=true;$('#p2pLane').hidden=true;$('#sourcesStatus').textContent=message}
function setupEpisodes(item){const picker=$('#episodePicker'),season=$('#seasonSelect'),episode=$('#episodeSelect');if(state.detailType!=='tv'){picker.hidden=true;return}picker.hidden=false;const seasons=(item.seasons||[]).filter(x=>Number(x.season_number)>0&&Number(x.episode_count)>0);season.innerHTML=seasons.map(x=>`<option value="${Number(x.season_number)}" data-count="${Number(x.episode_count)}">${state.lang==='ar'?'الموسم':'Season'} ${Number(x.season_number)}</option>`).join('');if(!season.options.length)season.innerHTML='<option value="1" data-count="20">1</option>';const fill=()=>{const count=Math.max(1,Number(season.selectedOptions[0]?.dataset.count||20));episode.innerHTML=Array.from({length:count},(_,i)=>`<option value="${i+1}">${state.lang==='ar'?'الحلقة':'Episode'} ${i+1}</option>`).join('')};fill();season.onchange=()=>{fill();loadSources()};episode.onchange=loadSources}
function sourceCard(server){return `<button class="source" data-server="${esc(server.id)}"><b>${esc(server.label)}</b><small>${server.lane==='p2p'?'RWL P2P':'RWL DIRECT'}</small></button>`}
function renderSources(servers){state.servers=servers||[];const direct=state.servers.filter(x=>x.lane==='direct'),p2p=state.servers.filter(x=>x.lane==='p2p');$('#directSources').innerHTML=direct.map(sourceCard).join('');$('#p2pSources').innerHTML=p2p.map(sourceCard).join('');$('#directLane').hidden=!direct.length;$('#p2pLane').hidden=!p2p.length;$('#sourcesStatus').textContent=state.servers.length?`${state.servers.length} ${state.lang==='ar'?'سيرفر متاح':'servers available'}`:(state.lang==='ar'?'لا يوجد سيرفر متاح حاليًا':'No server is currently available')}
function sourceQuery(){const x=state.detail;if(!x)return null;const p=new URLSearchParams({type:state.detailType,tmdb:String(x.id)});const imdb=x.external_ids?.imdb_id;if(imdb)p.set('imdb',imdb);if(state.detailType==='tv'){p.set('season',$('#seasonSelect').value||'1');p.set('episode',$('#episodeSelect').value||'1')}return p}
async function loadSources(){const q=sourceQuery();if(!q)return;resetSources(state.lang==='ar'?'جاري البحث عن السيرفرات…':'Finding servers…');try{const b=await api(`/v1/web/sources?${q.toString()}`);renderSources(b.servers||[])}catch(e){resetSources(state.lang==='ar'?'تعذر تحميل السيرفرات':'Could not load servers');console.error(e)}}
async function details(type,id){open('detailsOverlay');state.detail=null;state.detailType=type;$('#detailTitle').textContent='جاري التحميل…';$('#detailOverview').textContent='';$('#detailBackdrop').style.backgroundImage='';resetSources('');try{const b=await api(`/v1/tmdb/details?type=${encodeURIComponent(type)}&id=${encodeURIComponent(id)}&language=${state.lang==='ar'?'ar-SA':'en-US'}`),x=b.item;state.detail=x;$('#detailTitle').textContent=titleOf(x);$('#detailOverview').textContent=x.overview||'لا يوجد وصف متاح.';$('#detailMeta').textContent=[dateOf(x),type==='tv'?'مسلسل':'فيلم',x.runtime?`${x.runtime} دقيقة`:'',x.vote_average?`★ ${Number(x.vote_average).toFixed(1)}`:''].filter(Boolean).join(' • ');const bg=backdropURL(x);$('#detailBackdrop').style.backgroundImage=bg?`url("${bg}")`:'';setupEpisodes(x);await loadSources()}catch(e){$('#detailTitle').textContent='تعذر تحميل التفاصيل';$('#detailOverview').textContent=e.message}}
function setVideoURL(url,keepTime=false){const v=$('#webPlayer'),time=keepTime&&Number.isFinite(v.currentTime)?v.currentTime:0,wasPlaying=!v.paused;v.src=url;v.load();const resume=()=>{if(time>0){try{v.currentTime=time}catch{}}if(wasPlaying||!keepTime)v.play().catch(()=>{});v.removeEventListener('loadedmetadata',resume)};v.addEventListener('loadedmetadata',resume)}
function playServer(server){state.activeServer=server;$('#playerTitle').textContent=titleOf(state.detail||{});$('#playerServer').textContent=server.label;const qualities=server.qualities||[];$('#qualityButtons').innerHTML=qualities.map((q,i)=>`<button class="quality" data-quality="${i}">${esc(q.label||`Q${i+1}`)}</button>`).join('');setVideoURL(server.url,false);open('playerOverlay')}
function closePlayer(){const v=$('#webPlayer');v.pause();v.removeAttribute('src');v.load();state.activeServer=null;close('playerOverlay')}
async function enterFullscreen(){const v=$('#webPlayer');try{if(v.webkitEnterFullscreen){v.webkitEnterFullscreen();return}if(v.requestFullscreen){await v.requestFullscreen();return}if($('#playerOverlay').requestFullscreen)await $('#playerOverlay').requestFullscreen()}catch{toast(state.lang==='ar'?'تعذر فتح ملء الشاشة':'Fullscreen unavailable')}}
async function searchNow(q){q=q.trim();if(q.length<2){$('#searchGrid').innerHTML='';return}try{const b=await api(`/v1/tmdb/search?query=${encodeURIComponent(q)}&language=${state.lang==='ar'?'ar-SA':'en-US'}`);$('#searchGrid').innerHTML=(b.results||[]).filter(x=>x.media_type==='movie'||x.media_type==='tv').slice(0,16).map(card).join('')}catch(e){$('#searchGrid').innerHTML=`<div style="color:#999">${esc(e.message)}</div>`}}
function bindBody(){document.body.addEventListener('click',e=>{const c=e.target.closest('.card[data-id]');if(c){details(c.dataset.type,c.dataset.id);return}const s=e.target.closest('.source[data-server]');if(s){const server=state.servers.find(x=>x.id===s.dataset.server);if(server)playServer(server);return}const q=e.target.closest('[data-quality]');if(q&&state.activeServer){const item=state.activeServer.qualities?.[Number(q.dataset.quality)];if(item?.url)setVideoURL(item.url,true)}})}
function applyLang(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';$('#langBtn').textContent=state.lang==='ar'?'AR':'EN';$('#trendingTitle').textContent=state.lang==='ar'?'الأكثر مشاهدة هذا الأسبوع':'Top This Week';$('#moviesTitle').textContent=state.lang==='ar'?'أفلام شائعة':'Popular Movies';$('#tvTitle').textContent=state.lang==='ar'?'مسلسلات شائعة':'Popular TV Shows';$('#sourcesTitle').textContent=state.lang==='ar'?'المصادر':'Sources';$('#seasonLabel').textContent=state.lang==='ar'?'الموسم':'Season';$('#episodeLabel').textContent=state.lang==='ar'?'الحلقة':'Episode';$('#reloadSources').textContent=state.lang==='ar'?'تحديث السيرفرات':'Refresh servers';$('#fullScreenBtn').textContent=state.lang==='ar'?'⛶ ملء الشاشة':'⛶ Full screen'}
function init(){applyLang();bindBody();$('#searchBtn').onclick=()=>{open('searchOverlay');setTimeout(()=>$('#searchInput').focus(),80)};$('#heroRefresh').onclick=loadHome;$('#heroDetails').onclick=()=>state.hero&&details(typeOf(state.hero),state.hero.id);$('#langBtn').onclick=()=>{state.lang=state.lang==='ar'?'en':'ar';localStorage.setItem('rwlLang',state.lang);applyLang();loadHome()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));$('#searchInput').addEventListener('input',e=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(()=>searchNow(e.target.value),280)});document.querySelectorAll('.overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o){if(o.id==='playerOverlay')closePlayer();else o.classList.remove('open')}}));$('#reloadSources').onclick=loadSources;$('#closePlayer').onclick=closePlayer;$('#fullScreenBtn').onclick=enterFullscreen;$('#webPlayer').addEventListener('error',()=>toast(state.lang==='ar'?'تعذر تشغيل هذا السيرفر، جرّب سيرفر آخر':'This server could not play'));loadHome()}
init();
