'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const RWL_GATEWAY='https://rwl-movies-gateway.rwl98.workers.dev';
const IMG='https://image.tmdb.org/t/p/';
const themes={
  amethyst:{name:'RWL Cyan',primary:'#00BFEA',accent:'#00E5FF',bg:'#080A0F',card:'#12151E',top:'#0D1017'},
  cyberpunk:{name:'Cyberpunk Neon',primary:'#FF2A85',accent:'#00F0FF',bg:'#0C0812',card:'#160E1E',top:'#100A17'},
  emerald:{name:'Emerald Aurora',primary:'#10B981',accent:'#34D399',bg:'#060F0B',card:'#0E1A14',top:'#09140F'},
  sunset:{name:'Sunset Crimson',primary:'#FF3366',accent:'#FF9900',bg:'#0F080B',card:'#1A0E13',top:'#130A0E'},
  sapphire:{name:'Midnight Sapphire',primary:'#3B82F6',accent:'#60A5FA',bg:'#060B14',card:'#0E1726',top:'#09101C'},
  amber:{name:'Golden Amber',primary:'#F59E0B',accent:'#FCD34D',bg:'#0F0C06',card:'#1A160E',top:'#141009'},
  vampire:{name:'Vampire Red',primary:'#E50914',accent:'#FF4D4D',bg:'#0E0607',card:'#1A0C0E',top:'#14080A'},
  barbie:{name:'Pink Barbie',primary:'#FF1493',accent:'#FF80BF',bg:'#14050E',card:'#220A18',top:'#1A0713'}
};
const dockItems=[
  ['home','⌂','Home','الرئيسية',false],['discover','◈','Discover','استكشاف',true],['manga','▤','Manga','مانجا',true],
  ['books','▥','Books','كتب',true],['audiobooks','◉','Audiobooks','كتب صوتية',true],['music','♫','Music','موسيقى',true],
  ['anime','✦','Anime','أنمي',true],['livetv','▣','Live TV','بث مباشر',true],['addons','⊞','Addons','إضافات',true],
  ['downloads','⇩','Downloads','التنزيلات',true],['mylist','♥','My List','قائمتي',true],['settings','⚙','Settings','الإعدادات',false],['search','⌕','Search','بحث',true]
];
const state={
  gateway:RWL_GATEWAY, lang:localStorage.getItem('rwlLang')||'ar', theme:localStorage.getItem('rwlTheme')||'amethyst',
  glass:localStorage.getItem('rwlGlass')!=='0', page:'home', home:null, hero:null, detail:null, detailType:null, servers:[], activeServer:null,
  searchTimer:null, playerMeta:null, music:[], musicTrack:null
};
function tr(ar,en){return state.lang==='ar'?ar:en}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function stripHtml(v){return String(v||'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ')}
function api(path){return fetch(state.gateway+path,{headers:{Accept:'application/json'}}).then(async r=>{let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.message||`HTTP_${r.status}`);return b})}
function openOverlay(id){$('#'+id).classList.add('open')}
function closeOverlay(id){$('#'+id).classList.remove('open')}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2400)}
function typeOf(x){return x?.media_type==='tv'||(!x?.title&&x?.name)?'tv':'movie'}
function titleOf(x){return x?.title||x?.name||x?.original_title||x?.original_name||tr('بدون عنوان','Untitled')}
function yearOf(x){return String(x?.release_date||x?.first_air_date||'').slice(0,4)}
function poster(x,size='w500'){return x?.poster_path?`${IMG}${size}${x.poster_path}`:''}
function backdrop(x,size='original'){return x?.backdrop_path?`${IMG}${size}${x.backdrop_path}`:''}
function formatTime(sec){sec=Math.max(0,Number(sec)||0);const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=Math.floor(sec%60);return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function safeJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'')??fallback}catch{return fallback}}
function saveJSON(key,value){localStorage.setItem(key,JSON.stringify(value))}
function applyTheme(){const t=themes[state.theme]||themes.amethyst;const r=document.documentElement.style;r.setProperty('--primary',t.primary);r.setProperty('--accent',t.accent);r.setProperty('--bg',t.bg);r.setProperty('--card',t.card);r.setProperty('--top',t.top);r.setProperty('--glass',state.glass?'rgba(14,17,24,.68)':'rgba(14,17,24,.96)');document.querySelector('meta[name=theme-color]').content=t.bg}
function applyLang(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr'}
function dockEnabled(key){if(key==='home'||key==='settings')return true;return localStorage.getItem(`dock_${key}`)!=='0'}
function prefBool(key,def=true){const v=localStorage.getItem(`pref_${key}`);return v===null?def:v==='1'}
function renderDock(){const d=$('#dock');d.innerHTML=dockItems.filter(x=>dockEnabled(x[0])).map(([key,icon,en,ar])=>`<button class="dockBtn ${state.page===key?'active':''}" data-nav="${key}"><span class="dockIcon">${icon}</span><span>${esc(state.lang==='ar'?ar:en)}</span></button>`).join('')}
function setTopTitle(text){$('#topTitle').textContent=text}
function card(item){const type=typeOf(item),id=Number(item.id)||0,p=poster(item),t=titleOf(item),year=yearOf(item);return `<article class="posterCard ${p?'':'placeholderPoster'}" data-media-id="${id}" data-media-type="${type}">${p?`<img loading="lazy" src="${p}" alt="${esc(t)}">`:'RWL'}<div class="posterShade"></div><div class="posterCopy"><b>${esc(t)}</b><small>${esc([year,type==='tv'?tr('مسلسل','TV'):tr('فيلم','Movie'),item.vote_average?`★ ${Number(item.vote_average).toFixed(1)}`:''].filter(Boolean).join(' • '))}</small></div></article>`}
function row(items){return (items||[]).filter(x=>x?.id&&x.media_type!=='person').slice(0,24).map(card).join('')||`<div class="libraryEmpty">${tr('لا توجد نتائج','No results')}</div>`}
function section(title,items,id=''){return `<section class="section"><div class="sectionHead"><h2>${esc(title)}</h2></div><div class="horizontal" ${id?`id="${id}"`:''}>${row(items)}</div></section>`}
function pageHeader(title,desc,actions=''){return `<div class="pageTitle"><div><h1>${esc(title)}</h1><p>${esc(desc||'')}</p></div>${actions}</div>`}
async function navigate(page){if(page==='settings'){openSettings();return}if(page==='search'){openSearch();return}state.page=page;renderDock();const labels={home:tr('الرئيسية','Home'),discover:tr('استكشاف','Discover'),manga:'Manga',books:tr('الكتب','Books'),audiobooks:tr('الكتب الصوتية','Audiobooks'),music:tr('الموسيقى','Music'),anime:'Anime',livetv:'Live TV',addons:'Addons',downloads:tr('التنزيلات','Downloads'),mylist:tr('قائمتي','My List')};setTopTitle(labels[page]||'RWL Movies');window.scrollTo({top:0,behavior:'smooth'});try{if(page==='home')await renderHome();else if(page==='discover')await renderDiscover();else if(page==='music')await renderMusic();else if(page==='anime')await renderAniList('anime');else if(page==='manga')await renderAniList('manga');else if(page==='books')await renderBooks();else if(page==='audiobooks')renderAudiobooks();else if(page==='livetv')renderLiveTV();else if(page==='addons')renderAddons();else if(page==='downloads')renderDownloads();else if(page==='mylist')renderMyList()}catch(e){console.error(e);$('#view').innerHTML=`<div class="page">${pageHeader('RWL Movies',tr('تعذر تحميل هذه الصفحة','Could not load this page'))}<div class="libraryEmpty">${esc(e.message)}</div></div>`}}
async function renderHome(){if(!state.home){$('#view').innerHTML='<div class="page"><div class="libraryEmpty">RWL…</div></div>';state.home=await api(`/v1/tmdb/home?language=${state.lang==='ar'?'ar-SA':'en-US'}`)}const h=state.home;state.hero=(h.trending||[]).find(x=>x.media_type!=='person')||h.movies?.[0]||h.tv?.[0];const hero=state.hero||{},bg=backdrop(hero);const continueItems=continueWatchingItems();$('#view').innerHTML=`<section class="hero" style="${bg?`background-image:url('${bg}')`:''}"><div class="heroCopy"><div class="eyebrow">${esc([yearOf(hero),typeOf(hero)==='tv'?tr('مسلسل','TV'):tr('فيلم','Movie'),hero.vote_average?`★ ${Number(hero.vote_average).toFixed(1)}`:''].filter(Boolean).join(' • '))}</div><h1>${esc(titleOf(hero))}</h1><p>${esc(hero.overview||tr('أفلام ومسلسلات RWL في مكان واحد.','Movies, series and your RWL library in one place.'))}</p><div class="actions"><button class="primary" data-hero-detail>ⓘ ${tr('التفاصيل','Details')}</button><button class="pill" data-nav="discover">✦ ${tr('استكشاف','Discover')}</button></div></div></section>${continueItems.length?section(tr('أكمل المشاهدة','Continue Watching'),continueItems):''}${section(tr('الأكثر مشاهدة هذا الأسبوع','Top This Week'),h.trending)}${section(tr('أفلام شائعة','Popular Movies'),h.movies)}${section(tr('مسلسلات شائعة','Popular TV'),h.tv)}`}
async function renderDiscover(){const b=await api(`/v1/tmdb/trending?type=all&window=week&language=${state.lang==='ar'?'ar-SA':'en-US'}`);$('#view').innerHTML=`<div class="page">${pageHeader(tr('استكشاف','Discover'),tr('أفلام ومسلسلات رائجة من مكتبة RWL.','Trending movies and series from the RWL catalog.'),`<div class="chips"><button class="chip active" data-discover="all">${tr('الكل','All')}</button><button class="chip" data-discover="movie">${tr('أفلام','Movies')}</button><button class="chip" data-discover="tv">${tr('مسلسلات','TV')}</button></div>`)}<div class="mediaGrid" id="discoverGrid">${row(b.results)}</div></div>`}
async function refreshDiscover(type){const b=await api(`/v1/tmdb/trending?type=${type}&window=week&language=${state.lang==='ar'?'ar-SA':'en-US'}`);$('#discoverGrid').innerHTML=row(b.results);$$('[data-discover]').forEach(x=>x.classList.toggle('active',x.dataset.discover===type))}
function favoriteKey(type,id){return `${type}:${id}`}
function favorites(){return safeJSON('rwlFavorites',[])}
function isFavorite(type,id){return favorites().some(x=>x.key===favoriteKey(type,id))}
function toggleFavorite(){if(!state.detail)return;let list=favorites();const key=favoriteKey(state.detailType,state.detail.id);if(list.some(x=>x.key===key))list=list.filter(x=>x.key!==key);else list.unshift({key,type:state.detailType,item:state.detail});saveJSON('rwlFavorites',list.slice(0,100));updateFavoriteButton();toast(isFavorite(state.detailType,state.detail.id)?tr('تمت الإضافة إلى قائمتي','Added to My List'):tr('تمت الإزالة من قائمتي','Removed from My List'))}
function updateFavoriteButton(){if(!state.detail)return;$('#favoriteBtn').textContent=isFavorite(state.detailType,state.detail.id)?`♥ ${tr('في قائمتي','In My List')}`:`♡ ${tr('قائمتي','My List')}`}
function renderMyList(){const list=favorites().map(x=>x.item);$('#view').innerHTML=`<div class="page">${pageHeader(tr('قائمتي','My List'),tr('المفضلة والمحفوظات الخاصة بك.','Your favorites and saved titles.'))}<div class="mediaGrid">${row(list)}</div></div>`}
function resetSources(msg=''){state.servers=[];$('#directSources').innerHTML='';$('#totSources').innerHTML='';$('#directLane').hidden=true;$('#totLane').hidden=true;$('#sourcesStatus').textContent=msg}
function setupEpisodes(item){const picker=$('#episodePicker'),s=$('#seasonSelect'),e=$('#episodeSelect');if(state.detailType!=='tv'){picker.hidden=true;return}picker.hidden=false;const seasons=(item.seasons||[]).filter(x=>Number(x.season_number)>0&&Number(x.episode_count)>0);s.innerHTML=seasons.map(x=>`<option value="${Number(x.season_number)}" data-count="${Number(x.episode_count)}">${tr('الموسم','Season')} ${Number(x.season_number)}</option>`).join('')||'<option value="1" data-count="20">1</option>';const fill=()=>{const c=Math.max(1,Number(s.selectedOptions[0]?.dataset.count||20));e.innerHTML=Array.from({length:c},(_,i)=>`<option value="${i+1}">${tr('الحلقة','Episode')} ${i+1}</option>`).join('')};fill();s.onchange=()=>{fill();loadSources()};e.onchange=loadSources}
function sourceQuery(){const x=state.detail;if(!x)return null;const p=new URLSearchParams({type:state.detailType,tmdb:String(x.id)});if(x.external_ids?.imdb_id)p.set('imdb',x.external_ids.imdb_id);if(state.detailType==='tv'){p.set('season',$('#seasonSelect').value||'1');p.set('episode',$('#episodeSelect').value||'1')}return p}
function sourceCard(s){const lane=s.lane==='p2p'?'RWL TOT':'RWL DIRECT';return `<button class="source" data-server="${esc(s.id)}"><b>${esc(s.label)}</b><small>${lane}</small></button>`}
function renderSources(list){state.servers=list||[];const direct=state.servers.filter(x=>x.lane==='direct'),tot=state.servers.filter(x=>x.lane==='p2p');$('#directSources').innerHTML=direct.map(sourceCard).join('');$('#totSources').innerHTML=tot.map(sourceCard).join('');$('#directLane').hidden=!direct.length;$('#totLane').hidden=!tot.length;$('#sourcesStatus').textContent=state.servers.length?`${state.servers.length} ${tr('سيرفر متاح','servers available')}`:tr('لا يوجد سيرفر متاح حاليًا','No server available')}
async function loadSources(){const q=sourceQuery();if(!q)return;resetSources(tr('جاري البحث عن السيرفرات…','Finding servers…'));try{const b=await api(`/v1/web/sources?${q}`);renderSources(b.servers||[])}catch(e){resetSources(tr('تعذر تحميل السيرفرات','Could not load servers'));console.error(e)}}
async function details(type,id){openOverlay('detailsOverlay');state.detail=null;state.detailType=type;$('#detailTitle').textContent='RWL…';$('#detailOverview').textContent='';$('#detailBackdrop').style.backgroundImage='';resetSources();try{const b=await api(`/v1/tmdb/details?type=${encodeURIComponent(type)}&id=${encodeURIComponent(id)}&language=${state.lang==='ar'?'ar-SA':'en-US'}`);const x=b.item;state.detail=x;$('#detailTitle').textContent=titleOf(x);$('#detailOverview').textContent=x.overview||tr('لا يوجد وصف متاح.','No overview available.');$('#detailMeta').textContent=[yearOf(x),type==='tv'?tr('مسلسل','TV'):tr('فيلم','Movie'),x.runtime?`${x.runtime} ${tr('دقيقة','min')}`:'',x.vote_average?`★ ${Number(x.vote_average).toFixed(1)}`:''].filter(Boolean).join(' • ');const bg=backdrop(x);$('#detailBackdrop').style.backgroundImage=bg?`url('${bg}')`:'';setupEpisodes(x);updateFavoriteButton();await loadSources()}catch(e){$('#detailTitle').textContent=tr('تعذر التحميل','Could not load');$('#detailOverview').textContent=e.message}}
function bestUrl(server){return server?.qualities?.[0]?.url||server?.url||''}
function playServer(server){state.activeServer=server;const url=bestUrl(server);if(!url){toast(tr('لا يوجد رابط تشغيل','No playback URL'));return}const q=server.qualities||[];$('#qualityMenu').innerHTML=[`<button data-quality="master">AUTO</button>`,...q.map((x,i)=>`<button data-quality="${i}">${esc(x.label||`Q${i+1}`)}</button>`)].join('');$('#qualityBtn').textContent=q[0]?.label||'AUTO';$('#playerTitle').textContent=titleOf(state.detail);$('#playerServer').textContent=server.label;$('#playerLane').textContent=server.lane==='p2p'?'RWL TOT':'RWL DIRECT';state.playerMeta={type:state.detailType,item:state.detail,server:server.label,lane:server.lane};setVideoUrl(url,false);openOverlay('playerOverlay')}
function setVideoUrl(url,resume){const v=$('#webPlayer');const time=resume?v.currentTime:resumePositionFor(state.playerMeta);const wasPlaying=resume&&!v.paused;v.src=url;v.load();v.addEventListener('loadedmetadata',()=>{if(time>0&&Number.isFinite(time))try{v.currentTime=Math.min(time,Math.max(0,v.duration-1))}catch{}if(wasPlaying)v.play().catch(()=>{})},{once:true});updatePlayerUI()}
function continueWatching(){return safeJSON('rwlContinue',[])}
function continueWatchingItems(){return continueWatching().map(x=>x.item).filter(Boolean).slice(0,12)}
function resumePositionFor(meta){if(!meta?.item)return 0;const k=favoriteKey(meta.type,meta.item.id);return Number(continueWatching().find(x=>x.key===k)?.position||0)}
function saveProgress(){const v=$('#webPlayer');const m=state.playerMeta;if(!m?.item||!Number.isFinite(v.currentTime)||v.currentTime<5)return;let list=continueWatching();const key=favoriteKey(m.type,m.item.id);list=list.filter(x=>x.key!==key);if(Number.isFinite(v.duration)&&v.duration>0&&v.currentTime/v.duration<.94)list.unshift({key,type:m.type,item:m.item,position:v.currentTime,duration:v.duration,updated:Date.now()});saveJSON('rwlContinue',list.slice(0,24))}
function closePlayer(){saveProgress();const v=$('#webPlayer');v.pause();v.removeAttribute('src');v.load();closeOverlay('playerOverlay')}
function seekVideo(delta){const v=$('#webPlayer');if(!Number.isFinite(v.duration))return;v.currentTime=Math.max(0,Math.min(v.duration,v.currentTime+delta));updatePlayerUI()}
function toggleVideo(){const v=$('#webPlayer');if(v.paused)v.play().catch(()=>toast(tr('اضغط تشغيل مرة أخرى','Tap play again')));else v.pause()}
function updatePlayerUI(){const v=$('#webPlayer'),stage=$('#videoStage');stage.classList.toggle('paused',v.paused);$('#playPauseBtn').textContent=v.paused?'▶':'❚❚';$('#centerPlay').textContent=v.paused?'▶':'❚❚';$('#muteBtn').textContent=v.muted||v.volume===0?'🔇':'🔊';$('#timeText').textContent=`${formatTime(v.currentTime)} / ${formatTime(v.duration)}`;$('#seekBar').value=Number.isFinite(v.duration)&&v.duration>0?Math.round(v.currentTime/v.duration*1000):0;$('#volumeBar').value=v.muted?0:v.volume}
function openNativeVideoFullscreen(){const v=$('#webPlayer');try{if(typeof v.webkitEnterFullscreen==='function'){v.webkitEnterFullscreen();return}if(v.requestFullscreen)v.requestFullscreen()}catch{toast(tr('مشغل الآيفون غير متاح لهذا المصدر','Native iPhone player is unavailable for this source'))}}
function openWebFullscreen(){const stage=$('#videoStage');try{if(stage.requestFullscreen)stage.requestFullscreen();else openNativeVideoFullscreen()}catch{openNativeVideoFullscreen()}}
function toggleQualityMenu(){$('#qualityMenu').classList.toggle('open')}
async function renderMusic(query=''){const path=`/v1/web/music${query?`?query=${encodeURIComponent(query)}`:''}`;const b=await api(path);state.music=b.tracks||[];$('#view').innerHTML=`<div class="page">${pageHeader(tr('الموسيقى','Music'),tr('مكتبة الموسيقى والمشغل المصغر مستوحاة من RWL Music. المعاينات المتاحة تُشغّل مباشرة.','Music library and mini player inspired by RWL Music. Available previews play directly.'),`<button class="pill" id="musicSearchBtn">⌕ ${tr('بحث','Search')}</button>`)}<div class="musicGrid">${state.music.map((x,i)=>`<article class="track"><img src="${esc(x.cover||'assets/rwl-icon.png')}" alt=""><div class="trackMeta"><b>${esc(x.title)}</b><small>${esc(x.artist)}${x.album?` • ${esc(x.album)}`:''}</small></div><button data-track="${i}">▶</button></article>`).join('')}</div></div>`}
function playTrack(i){const t=state.music[i];if(!t?.preview){toast(tr('لا توجد معاينة متاحة لهذه الأغنية','No preview available for this track'));return}state.musicTrack=t;const a=$('#musicAudio');a.src=t.preview;$('#miniCover').src=t.cover||'assets/rwl-icon.png';$('#miniTitle').textContent=t.title;$('#miniArtist').textContent=t.artist;$('#miniPlayer').hidden=false;a.play().catch(()=>{});updateMusicUI()}
function updateMusicUI(){const a=$('#musicAudio');$('#miniPlay').textContent=a.paused?'▶':'❚❚';$('#miniSeek').value=Number.isFinite(a.duration)&&a.duration>0?Math.round(a.currentTime/a.duration*1000):0}
function aniTitle(x){return x?.title?.userPreferred||x?.title?.english||x?.title?.romaji||x?.title?.native||'Untitled'}
async function renderAniList(kind,query=''){const b=await api(`/v1/web/anilist?kind=${kind}${query?`&query=${encodeURIComponent(query)}`:''}`);const title=kind==='anime'?'Anime':'Manga',desc=kind==='anime'?tr('الأنمي الرائج ومكتبتك.','Trending anime and your library.'):tr('استكشف المانجا والويب تون.','Browse manga and webtoons.');$('#view').innerHTML=`<div class="page">${pageHeader(title,desc,`<button class="pill" data-catalog-search="${kind}">⌕ ${tr('بحث','Search')}</button>`)}<div class="mediaGrid">${(b.items||[]).map(x=>`<article class="posterCard" data-anilist="${x.id}" data-kind="${kind}" data-json="${encodeURIComponent(JSON.stringify(x))}"><img src="${esc(x.cover)}" alt="${esc(aniTitle(x))}"><div class="posterShade"></div><div class="posterCopy"><b>${esc(aniTitle(x))}</b><small>${esc([x.year,x.format,x.score?`★ ${(x.score/10).toFixed(1)}`:''].filter(Boolean).join(' • '))}</small></div></article>`).join('')}</div></div>`}
function showAniListCard(el){let x={};try{x=JSON.parse(decodeURIComponent(el.dataset.json||''))}catch{}const name=aniTitle(x),kind=el.dataset.kind;$('#view').insertAdjacentHTML('afterbegin','');toast(`${name} · ${kind==='anime'?'Anime':'Manga'}`)}
async function renderBooks(query=''){const b=await api(`/v1/web/books${query?`?query=${encodeURIComponent(query)}`:''}`);$('#view').innerHTML=`<div class="page">${pageHeader(tr('الكتب','Books'),tr('مكتبة كتب RWL على الويب.','RWL Books library on the web.'),`<button class="pill" id="bookSearchBtn">⌕ ${tr('بحث','Search')}</button>`)}<div class="mediaGrid">${(b.books||[]).map(x=>`<article class="posterCard" data-book-link="${esc(x.infoLink)}">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.title)}">`:'<div class="placeholderPoster">RWL</div>'}<div class="posterShade"></div><div class="posterCopy"><b>${esc(x.title)}</b><small>${esc((x.authors||[]).join(', '))}</small></div></article>`).join('')}</div></div>`}
function renderAudiobooks(){const library=safeJSON('rwlAudioBooks',[]);$('#view').innerHTML=`<div class="page">${pageHeader(tr('الكتب الصوتية','Audiobooks'),tr('أضف ملفاتك الصوتية المحلية واستمع لها من مكتبة RWL.','Add your local audio files and listen from your RWL library.'))}<div class="uploadBox"><p>${tr('اختر ملفات صوتية من جهازك','Choose audio files from your device')}</p><input id="audioBookFiles" type="file" accept="audio/*" multiple></div><div class="listRows" id="audioBookList">${library.length?library.map(x=>`<div class="listRow"><b>${esc(x.name)}</b><small>${esc(x.size||'')}</small></div>`).join(''):`<div class="libraryEmpty">${tr('لا توجد كتب صوتية محلية بعد','No local audiobooks yet')}</div>`}</div></div>`}
function handleAudioBookFiles(files){const list=[...files].map(f=>({name:f.name,size:`${(f.size/1024/1024).toFixed(1)} MB`}));saveJSON('rwlAudioBooks',list);renderAudiobooks();toast(tr('تمت إضافة الملفات للمكتبة المحلية','Files added to local library'))}
function renderLiveTV(){const portals=safeJSON('rwlIptvPortals',[]);$('#view').innerHTML=`<div class="page">${pageHeader('Live TV',tr('مكتبة IPTV محلية. يمكنك حفظ بيانات البوابة في هذا الجهاز.','Local IPTV library. Portal details stay on this device.'))}<div class="contentCard"><h3>${tr('إضافة بوابة IPTV','Add IPTV portal')}</h3><div class="listRows"><input class="searchInput" id="iptvName" placeholder="Name"><input class="searchInput" id="iptvUrl" placeholder="M3U / Portal URL"><button class="primary" id="saveIptv">${tr('حفظ محليًا','Save locally')}</button></div></div><section class="section"><div class="sectionHead"><h2>${tr('البوابات','Portals')}</h2></div><div class="listRows">${portals.length?portals.map((x,i)=>`<div class="listRow"><div><b>${esc(x.name)}</b><small>${esc(x.url)}</small></div><button class="pill" data-remove-iptv="${i}">×</button></div>`).join(''):`<div class="libraryEmpty">${tr('لا توجد بوابات مضافة','No portals added')}</div>`}</div></section></div>`}
function renderAddons(){$('#view').innerHTML=`<div class="page">${pageHeader('Addons',tr('مصادر RWL مرتبطة من الـGateway. أسماء المزودين لا تظهر للمستخدم.','RWL sources are connected through the Gateway. Provider identities stay hidden from the UI.'))}<div class="statGrid"><div class="contentCard stat"><b>RWL DIRECT</b><small>${tr('مصادر HTTP/Streaming','HTTP / streaming sources')}</small></div><div class="contentCard stat"><b>RWL TOT</b><small>${tr('مصادر torrent المحلولة عبر الخدمة السحابية','Torrent sources resolved by the cloud service')}</small></div><div class="contentCard stat"><b>Gateway</b><small>${esc(state.gateway.replace(/^https?:\/\//,''))}</small></div></div></div>`}
function renderDownloads(){const c=continueWatching();$('#view').innerHTML=`<div class="page">${pageHeader(tr('التنزيلات','Downloads'),tr('مكتبة الويب تحتفظ بالتقدم محليًا. تنزيلات التطبيق الأصلية تبقى منفصلة عن Safari.','The web library keeps playback progress locally. Native-app downloads remain separate from Safari.'))}<div class="contentCard"><b>${c.length}</b> ${tr('عناصر محفوظة كتقدم مشاهدة','saved playback-progress items')}</div></div>`}
function saveIptv(){const name=$('#iptvName').value.trim(),url=$('#iptvUrl').value.trim();if(!name||!/^https?:\/\//i.test(url)){toast(tr('اكتب اسم ورابط صحيح','Enter a name and valid URL'));return}const list=safeJSON('rwlIptvPortals',[]);list.push({name,url});saveJSON('rwlIptvPortals',list);renderLiveTV()}
function openSearch(){openOverlay('searchOverlay');setTimeout(()=>$('#searchInput').focus(),80)}
async function searchNow(q){q=q.trim();if(q.length<2){$('#searchGrid').innerHTML='';return}try{const b=await api(`/v1/tmdb/search?query=${encodeURIComponent(q)}&language=${state.lang==='ar'?'ar-SA':'en-US'}`);$('#searchGrid').innerHTML=row((b.results||[]).filter(x=>x.media_type==='movie'||x.media_type==='tv'))}catch(e){$('#searchGrid').innerHTML=`<div class="libraryEmpty">${esc(e.message)}</div>`}}
function settingsMarkup(){
  const setting=(title,sub,control)=>`<div class="settingRow"><div class="settingText"><b>${title}</b><small>${sub}</small></div>${control}</div>`;
  const sw=(key,checked=prefBool(key))=>`<label class="switch"><input data-web-pref="${key}" type="checkbox" ${checked?'checked':''}><span></span></label>`;
  return `<div class="settingsGroup"><h3>${tr('الواجهة','INTERFACE')}</h3>
    ${setting(tr('لغة التطبيق','App Language'),tr('تغيير واجهة RWL كاملة','Change the full RWL interface language'),`<select id="langSelect"><option value="ar" ${state.lang==='ar'?'selected':''}>العربية</option><option value="en" ${state.lang==='en'?'selected':''}>English</option></select>`)}
    ${setting(tr('Appearance & Interface','Appearance & Interface'),tr('Liquid Glass والثيمات وتخصيص الواجهة','Liquid Glass, color themes and interface customization'),'<span>›</span>')}
    ${setting('Liquid Glass',tr('الزجاج والتمويه للواجهة','Glass and blur interface'),`<label class="switch"><input id="glassToggle" type="checkbox" ${state.glass?'checked':''}><span></span></label>`)}
  </div>
  <div class="settingsGroup"><h3>${tr('الثيمات','THEMES')}</h3><div class="themeGrid">${Object.entries(themes).map(([id,x])=>`<button class="themeTile ${state.theme===id?'active':''}" data-theme="${id}"><div class="themeSwatch" style="background:linear-gradient(135deg,${x.primary},${x.accent},${x.bg})"></div><b>${esc(x.name)}</b></button>`).join('')}</div></div>
  <div class="settingsGroup"><h3>${tr('الشريط','DOCK')}</h3>${dockItems.filter(x=>x[4]).map(([key,,en,ar])=>setting(state.lang==='ar'?ar:en,tr('إظهار أو إخفاء من شريط RWL','Show or hide from the RWL dock'),`<label class="switch"><input data-dock-toggle="${key}" type="checkbox" ${dockEnabled(key)?'checked':''}><span></span></label>`)).join('')}</div>
  <div class="settingsGroup"><h3>${tr('التشغيل والخدمات','PLAYBACK & SERVICES')}</h3>
    ${setting(tr('Video & Upscaling','Video & Upscaling'),tr('خيارات المشغل والفول سكرين ومشغل الآيفون','Player, fullscreen and iPhone native-player controls'),'<span>›</span>')}
    ${setting(tr('Debrid & Cloud Streaming','Debrid & Cloud Streaming'),tr('المفاتيح الخاصة تبقى داخل RWL Gateway فقط','Private credentials stay inside RWL Gateway only'),'<span>✓</span>')}
    ${setting('Addons',tr('كتالوجات ومصادر RWL','RWL catalogs and content sources'),'<span>›</span>')}
    ${setting(tr('Built-in Providers','Built-in Providers'),tr('مصادر البث المباشر وترتيب السيرفرات','Direct streaming sources and server priority'),'<span>RWL DIRECT</span>')}
    ${setting('RWL TOT',tr('مصادر torrent تُحل خلف RWL Gateway بدون كشف أي مفتاح','Torrent sources resolve behind RWL Gateway without exposing any key'),'<span>✓</span>')}
    ${setting(tr('TV Airing Calendar','TV Airing Calendar'),tr('إظهار تقويم الحلقات القادمة','Show upcoming episode calendar'),sw('calendar'))}
    ${setting(tr('AI Recommendation Quiz','AI Recommendation Quiz'),tr('تفضيلات توصيات RWL على هذا الجهاز','RWL recommendation preferences on this device'),sw('aiQuiz'))}
    ${setting('Discord Rich Presence',tr('واجهة الخيار موجودة؛ التكامل المكتبي الأصلي غير متاح داخل Safari','Setting surface mirrored; native desktop RPC is not available in Safari'),sw('discord',false))}
    ${setting('Trakt.tv Sync',tr('مزامنة قائمة المشاهدة والسجل بين الأجهزة','Cross-device watchlist and history synchronization'),'<span>›</span>')}
    ${setting('Simkl Sync',tr('مزامنة الأفلام والمسلسلات والأنمي','Movies, TV and Anime synchronization'),'<span>›</span>')}
  </div>
  <div class="settingsGroup"><h3>${tr('النسخ والبرنامج','DATA & APP')}</h3>
    ${setting(tr('Backup & Restore','Backup & Restore'),tr('تصدير أو استيراد إعدادات الموقع والمكتبات','Export or import web settings and libraries'),'<span>JSON</span>')}
    ${setting(tr('App Updates','App Updates'),tr('GitHub Pages يتحدث عند رفع ملفات النسخة الجديدة','GitHub Pages updates when the new web files are deployed'),'<span>v5</span>')}
    <div class="actions"><button class="pill" id="exportSettings">${tr('تصدير JSON','Export JSON')}</button><button class="pill" id="importSettings">${tr('استيراد JSON','Import JSON')}</button><input type="file" accept="application/json" id="importFile" hidden></div>
  </div>
  <div class="settingsGroup"><h3>${tr('حول','ABOUT')}</h3>${setting('RWL Movies Web','PWA · GitHub Pages + RWL Gateway','<span>v5</span>')}${setting(tr('المطور','Developer'),'Raed Alruwaili','<span>RWL</span>')}</div>`
}
function openSettings(){$('#settingsContent').innerHTML=settingsMarkup();openOverlay('settingsOverlay')}
function exportSettings(){const data={lang:state.lang,theme:state.theme,glass:state.glass,dock:Object.fromEntries(dockItems.map(x=>[x[0],dockEnabled(x[0])])),favorites:favorites(),continue:continueWatching(),iptv:safeJSON('rwlIptvPortals',[]),audiobooks:safeJSON('rwlAudioBooks',[])};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='RWL-Movies-Web-Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importSettings(file){try{const data=JSON.parse(await file.text());if(['ar','en'].includes(data.lang)){state.lang=data.lang;localStorage.setItem('rwlLang',state.lang)}if(themes[data.theme]){state.theme=data.theme;localStorage.setItem('rwlTheme',state.theme)}if(typeof data.glass==='boolean'){state.glass=data.glass;localStorage.setItem('rwlGlass',state.glass?'1':'0')}if(data.dock)Object.entries(data.dock).forEach(([k,v])=>localStorage.setItem(`dock_${k}`,v?'1':'0'));if(Array.isArray(data.favorites))saveJSON('rwlFavorites',data.favorites);if(Array.isArray(data.continue))saveJSON('rwlContinue',data.continue);if(Array.isArray(data.iptv))saveJSON('rwlIptvPortals',data.iptv);if(Array.isArray(data.audiobooks))saveJSON('rwlAudioBooks',data.audiobooks);applyLang();applyTheme();renderDock();openSettings();navigate('home');toast(tr('تم استيراد النسخة الاحتياطية','Backup imported'))}catch{toast(tr('ملف النسخة الاحتياطية غير صالح','Invalid backup file'))}}
function bindGlobal(){document.body.addEventListener('click',async e=>{const nav=e.target.closest('[data-nav]');if(nav){navigate(nav.dataset.nav);return}const media=e.target.closest('[data-media-id]');if(media){details(media.dataset.mediaType,media.dataset.mediaId);return}const source=e.target.closest('[data-server]');if(source){const s=state.servers.find(x=>x.id===source.dataset.server);if(s)playServer(s);return}const track=e.target.closest('[data-track]');if(track){playTrack(Number(track.dataset.track));return}const d=e.target.closest('[data-discover]');if(d){refreshDiscover(d.dataset.discover);return}const th=e.target.closest('[data-theme]');if(th){state.theme=th.dataset.theme;localStorage.setItem('rwlTheme',state.theme);applyTheme();openSettings();return}const an=e.target.closest('[data-anilist]');if(an){showAniListCard(an);return}const book=e.target.closest('[data-book-link]');if(book?.dataset.bookLink){window.open(book.dataset.bookLink,'_blank','noopener');return}const rm=e.target.closest('[data-remove-iptv]');if(rm){const list=safeJSON('rwlIptvPortals',[]);list.splice(Number(rm.dataset.removeIptv),1);saveJSON('rwlIptvPortals',list);renderLiveTV();return}if(e.target.closest('[data-hero-detail]')&&state.hero){details(typeOf(state.hero),state.hero.id);return}if(e.target.id==='musicSearchBtn'){const q=prompt(tr('ابحث عن أغنية أو فنان','Search track or artist'));if(q)renderMusic(q);return}if(e.target.id==='bookSearchBtn'){const q=prompt(tr('ابحث عن كتاب','Search books'));if(q)renderBooks(q);return}const cs=e.target.closest('[data-catalog-search]');if(cs){const q=prompt(tr('بحث','Search'));if(q)renderAniList(cs.dataset.catalogSearch,q);return}if(e.target.id==='saveIptv'){saveIptv();return}if(e.target.id==='exportSettings'){exportSettings();return}if(e.target.id==='importSettings'){$('#importFile').click();return}});document.body.addEventListener('change',e=>{if(e.target.id==='langSelect'){state.lang=e.target.value;localStorage.setItem('rwlLang',state.lang);applyLang();renderDock();openSettings();navigate(state.page)}if(e.target.id==='glassToggle'){state.glass=e.target.checked;localStorage.setItem('rwlGlass',state.glass?'1':'0');applyTheme()}if(e.target.matches('[data-dock-toggle]')){localStorage.setItem(`dock_${e.target.dataset.dockToggle}`,e.target.checked?'1':'0');renderDock()}if(e.target.matches('[data-web-pref]')){localStorage.setItem(`pref_${e.target.dataset.webPref}`,e.target.checked?'1':'0')}if(e.target.id==='importFile'&&e.target.files?.[0])importSettings(e.target.files[0]);if(e.target.id==='audioBookFiles')handleAudioBookFiles(e.target.files)});$$('[data-close]').forEach(b=>b.onclick=()=>closeOverlay(b.dataset.close));$$('.overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o){if(o.id==='playerOverlay')closePlayer();else closeOverlay(o.id)}}))}
function bindPlayer(){const v=$('#webPlayer'),stage=$('#videoStage');$('#playPauseBtn').onclick=toggleVideo;$('#centerPlay').onclick=toggleVideo;$('#back10Btn').onclick=()=>seekVideo(-10);$('#forward10Btn').onclick=()=>seekVideo(10);$('#tapBack').ondblclick=()=>{seekVideo(-10);flashTap('#tapBack')};$('#tapForward').ondblclick=()=>{seekVideo(10);flashTap('#tapForward')};$('#closePlayer').onclick=closePlayer;$('#seekBar').oninput=e=>{if(Number.isFinite(v.duration))v.currentTime=v.duration*Number(e.target.value)/1000};$('#volumeBar').oninput=e=>{v.muted=false;v.volume=Number(e.target.value);updatePlayerUI()};$('#muteBtn').onclick=()=>{v.muted=!v.muted;updatePlayerUI()};$('#qualityBtn').onclick=toggleQualityMenu;$('#nativeFullBtn').onclick=openNativeVideoFullscreen;$('#fullScreenBtn').onclick=openWebFullscreen;$('#qualityMenu').onclick=e=>{const b=e.target.closest('[data-quality]');if(!b||!state.activeServer)return;const url=b.dataset.quality==='master'?state.activeServer.url:state.activeServer.qualities?.[Number(b.dataset.quality)]?.url;if(url){$('#qualityBtn').textContent=b.textContent;setVideoUrl(url,true)}$('#qualityMenu').classList.remove('open')};['timeupdate','durationchange','play','pause','volumechange'].forEach(ev=>v.addEventListener(ev,()=>{updatePlayerUI();if(ev==='timeupdate'&&Math.floor(v.currentTime)%5===0)saveProgress()}));v.addEventListener('error',()=>toast(tr('تعذر تشغيل هذا السيرفر، جرّب سيرفر آخر','This server could not play. Try another server.')));let hide;const activity=()=>{stage.classList.remove('hideControls');clearTimeout(hide);if(!v.paused)hide=setTimeout(()=>stage.classList.add('hideControls'),3000)};stage.addEventListener('pointermove',activity);stage.addEventListener('click',activity)}
function flashTap(sel){const e=$(sel);e.classList.add('flash');setTimeout(()=>e.classList.remove('flash'),350)}
function bindMusic(){const a=$('#musicAudio');$('#miniPlay').onclick=()=>a.paused?a.play():a.pause();$('#miniSeek').oninput=e=>{if(Number.isFinite(a.duration))a.currentTime=a.duration*Number(e.target.value)/1000};['timeupdate','play','pause','ended'].forEach(x=>a.addEventListener(x,updateMusicUI))}
function bindFixed(){bindGlobal();bindPlayer();bindMusic();$('#globalSearchBtn').onclick=openSearch;$('#settingsBtn').onclick=openSettings;$('#searchInput').addEventListener('input',e=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(()=>searchNow(e.target.value),280)});$('#favoriteBtn').onclick=toggleFavorite;$('#reloadSources').onclick=loadSources}
async function init(){applyLang();applyTheme();renderDock();bindFixed();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});await navigate('home')}
init();
