'use strict';
const $ = s => document.querySelector(s);
const state = {gateway: localStorage.getItem('rwlGateway') || '', lang: localStorage.getItem('rwlLang') || 'ar', home:null, hero:null, searchTimer:null};
const imgBase = 'https://image.tmdb.org/t/p/';
function cleanGateway(v){try{const u=new URL(String(v||'').trim());if(u.protocol!=='https:')return '';return u.origin;}catch{return ''}}
function typeOf(x){return x.media_type==='tv'||(!x.title&&x.name)?'tv':'movie'}
function titleOf(x){return x.title||x.name||x.original_title||x.original_name||'Untitled'}
function dateOf(x){return (x.release_date||x.first_air_date||'').slice(0,4)}
function posterURL(x,size='w500'){return x?.poster_path?`${imgBase}${size}${x.poster_path}`:''}
function backdropURL(x,size='w1280'){return x?.backdrop_path?`${imgBase}${size}${x.backdrop_path}`:''}
function text(s){return String(s??'')}
function esc(s){return text(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)}
function setStatus(msg){$('#status').textContent=msg}
function open(id){$('#'+id).classList.add('open')}
function close(id){$('#'+id).classList.remove('open')}
async function api(path){if(!state.gateway)throw new Error('NO_GATEWAY');const r=await fetch(state.gateway+path,{headers:{Accept:'application/json'}});let b={};try{b=await r.json()}catch{}if(!r.ok||b.ok===false)throw new Error(b.message||`HTTP_${r.status}`);return b}
function card(item){const t=esc(titleOf(item)),year=esc(dateOf(item)),type=typeOf(item),id=Number(item.id)||0,p=posterURL(item);return `<article class="card ${p?'':'placeholder'}" data-id="${id}" data-type="${type}">${p?`<img loading="lazy" src="${p}" alt="${t}">`:'RWL'}<div class="cardShade"></div><div class="cardCopy"><b>${t}</b><small>${year}${year?' • ':''}${type==='tv'?'TV':'Movie'}${item.vote_average?` • ★ ${Number(item.vote_average).toFixed(1)}`:''}</small></div></article>`}
function row(el,items){$(el).innerHTML=(items||[]).filter(x=>x&&x.id&&(x.media_type!=='person')).slice(0,20).map(card).join('')||'<div style="color:#777;padding:20px">لا توجد نتائج</div>'}
function applyHero(item){if(!item)return;state.hero=item;const bg=backdropURL(item);$('#hero').style.backgroundImage=bg?`linear-gradient(125deg,#10172244,#21152355),url("${bg}")`:'';$('#heroTitle').textContent=titleOf(item);$('#heroOverview').textContent=item.overview||'لا يوجد وصف متاح.';$('#heroMeta').textContent=[dateOf(item),typeOf(item)==='tv'?'مسلسل':'فيلم',item.vote_average?`★ ${Number(item.vote_average).toFixed(1)}`:''].filter(Boolean).join(' • ')}
async function loadHome(){if(!state.gateway){setStatus('يحتاج ربط Gateway');open('settingsOverlay');return}setStatus('جاري التحميل…');try{const b=await api(`/v1/tmdb/home?language=${state.lang==='ar'?'ar-SA':'en-US'}`);state.home=b;row('#trendingRow',b.trending);row('#moviesRow',b.movies);row('#tvRow',b.tv);applyHero((b.trending||[]).find(x=>x.media_type!=='person')||b.movies?.[0]||b.tv?.[0]);setStatus('متصل بـ RWL Gateway')}catch(e){setStatus('تعذر الاتصال');toast(e.message==='TMDB_NOT_CONFIGURED'?'TMDB غير مفعّل في Gateway':'تحقق من رابط Gateway');open('settingsOverlay');$('#connection').textContent=`خطأ: ${e.message}`}}
async function details(type,id){open('detailsOverlay');$('#detailTitle').textContent='جاري التحميل…';$('#detailOverview').textContent='';$('#detailBackdrop').style.backgroundImage='';try{const b=await api(`/v1/tmdb/details?type=${encodeURIComponent(type)}&id=${encodeURIComponent(id)}&language=${state.lang==='ar'?'ar-SA':'en-US'}`),x=b.item;$('#detailTitle').textContent=titleOf(x);$('#detailOverview').textContent=x.overview||'لا يوجد وصف متاح.';$('#detailMeta').textContent=[dateOf(x),type==='tv'?'مسلسل':'فيلم',x.runtime?`${x.runtime} دقيقة`:'',x.vote_average?`★ ${Number(x.vote_average).toFixed(1)}`:''].filter(Boolean).join(' • ');const bg=backdropURL(x);$('#detailBackdrop').style.backgroundImage=bg?`url("${bg}")`:''}catch(e){$('#detailTitle').textContent='تعذر تحميل التفاصيل';$('#detailOverview').textContent=e.message}}
async function searchNow(q){q=q.trim();if(q.length<2){$('#searchGrid').innerHTML='';return}try{const b=await api(`/v1/tmdb/search?query=${encodeURIComponent(q)}&language=${state.lang==='ar'?'ar-SA':'en-US'}`);$('#searchGrid').innerHTML=(b.results||[]).filter(x=>x.media_type==='movie'||x.media_type==='tv').slice(0,16).map(card).join('')}catch(e){$('#searchGrid').innerHTML=`<div style="color:#999">${esc(e.message)}</div>`}}
async function testGateway(){const v=cleanGateway($('#gatewayInput').value);if(!v){$('#connection').textContent='الرابط غير صحيح. يجب أن يبدأ بـ https://';return}$('#connection').textContent='جاري الاختبار…';try{const r=await fetch(v+'/health');const b=await r.json();if(!r.ok||!b.ok)throw new Error('Health check failed');state.gateway=v;localStorage.setItem('rwlGateway',v);$('#connection').textContent=`متصل: ${b.service||'RWL Gateway'} ${b.version||''}`;toast('تم حفظ Gateway');setTimeout(()=>{close('settingsOverlay');loadHome()},450)}catch(e){$('#connection').textContent='تعذر الوصول إلى Gateway: '+e.message}}
function bindCards(){document.body.addEventListener('click',e=>{const c=e.target.closest('.card[data-id]');if(c)details(c.dataset.type,c.dataset.id)})}
function applyLang(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';$('#langBtn').textContent=state.lang==='ar'?'AR':'EN';$('#trendingTitle').textContent=state.lang==='ar'?'الأكثر مشاهدة هذا الأسبوع':'Top This Week';$('#moviesTitle').textContent=state.lang==='ar'?'أفلام شائعة':'Popular Movies';$('#tvTitle').textContent=state.lang==='ar'?'مسلسلات شائعة':'Popular TV Shows'}
qaInit();
function qaInit(){applyLang();bindCards();$('#gatewayInput').value=state.gateway;$('#settingsBtn').onclick=()=>open('settingsOverlay');$('#searchBtn').onclick=()=>{open('searchOverlay');setTimeout(()=>$('#searchInput').focus(),80)};$('#saveGateway').onclick=testGateway;$('#clearGateway').onclick=()=>{localStorage.removeItem('rwlGateway');state.gateway='';$('#gatewayInput').value='';$('#connection').textContent='تم مسح الرابط';setStatus('غير متصل')};$('#heroRefresh').onclick=loadHome;$('#heroDetails').onclick=()=>state.hero&&details(typeOf(state.hero),state.hero.id);$('#langBtn').onclick=()=>{state.lang=state.lang==='ar'?'en':'ar';localStorage.setItem('rwlLang',state.lang);applyLang();loadHome()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));$('#searchInput').addEventListener('input',e=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(()=>searchNow(e.target.value),280)});document.querySelectorAll('.overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.remove('open')}));loadHome()}
